# Generated by Django 2.2.14 on 2020-08-16 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HomeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
                ('bedrooms', models.IntegerField(default=0)),
                ('year_built', models.IntegerField(null=True)),
                ('home_size', models.IntegerField(blank=True)),
                ('property_size', models.IntegerField(blank=True)),
                ('price', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('address', models.CharField(max_length=200)),
                ('area_unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.AreaUnit')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.City')),
                ('home_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.HomeType')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.State')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='location.ZipCode')),
            ],
            options={
                'unique_together': {('address', 'city', 'state', 'zip_code')},
            },
        ),
        migrations.CreateModel(
            name='SaleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_date', models.DateField()),
                ('sold_price', models.DecimalField(decimal_places=3, default=0.0, max_digits=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='property.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200)),
                ('external_link', models.URLField()),
                ('source', models.CharField(choices=[('zillow', 'Zillow')], default='zillow', max_length=100)),
                ('rent_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=20, null=True)),
                ('estimated_rent', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=20, null=True)),
                ('estimated_rent_updated', models.DateField(blank=True, null=True)),
                ('estimated_sale_price', models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=20, null=True)),
                ('estimated_sale_price_updated', models.DateField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingTaxInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Listing')),
            ],
            options={
                'unique_together': {('year', 'listing')},
            },
        ),
    ]
