# Generated by Django 2.2.14 on 2020-08-17 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salehistory',
            name='sold_date',
            field=models.DateField(null=True),
        ),
    ]
